### ISSUE TITLE
下载地址已经失效

### ISSUE THREAD

**Issue by zhaoshg** [diaozxin007/youdao#3]
你好，下载地址已经失效了，能否再维护下呢？

**Comment by diaozxin007** [comment]
https://xilidou.oss-cn-beijing.aliyuncs.com/file/%E6%9C%89%E9%81%93%E5%AD%97%E5%85%B8%E5%A8%81%E5%8A%9B%E5%8A%A0%E5%BC%BA%E7%89%88.alfredworkflow

**Comment by diaozxin007** [comment]
> 你好，下载地址已经失效了，能否再维护下呢？
